AppendTo[$Path, "D:\\Programming\\mathematicaPackages\\mathematica_notebook_codes\\fitBitDataAnalysis"];
Needs["DatabaseLink`"];
Needs["fitBitDataImport`"];
FBDIGetRecordTypes[];
FBDIPlotActiveMinutes[];
FBDIPlotDefaultZones[];
FBDIPlotCaloriesByDay[];
FBDIPlotCaloriesByWeek[];
FBDIPlotHeartRateByDay[];
FBDIPlotHeartRateByHour[];
FBDIPlotStepsByDay[];
FBDIPlotStepsByWeek[];
FBDIPlotHRCaloriesStepsMinutely[];
FBDIPlotHRCaloriesStepsHourly[];